### PR TITLE
Compile with rolling

### PR DESCRIPTION
**Pull request by doisyg**
Bag and executor API breaks with rolling / upcoming galactic. This PR fixes it (though it may be more appropriate to create a new branch ?)

### CODE REVIEW

**Comment by doisyg** [comment]
in order to work with rolling / galactic. See here : https://github.com/facontidavide/PlotJuggler/issues/422

**Comment by facontidavide** [comment]
Yes, I need to create a different branch. Thanks for contributing. I will try to find time this week to release the packages

**Comment by doisyg** [comment]
Great!
I think there is an issue with the libDataStreamROS2  plugin that I did not take time to test and debug, see https://github.com/facontidavide/PlotJuggler/issues/422
I may take a look at the end of the week if you don't do it before

**Comment by salmagro** [comment]
Dear @doisyg, 
I have seen your commits in the rolling branch in this repo, but I am not sure which branch should I use in https://github.com/facontidavide/PlotJuggler.git

I appreciate your comments.

**Pull request merged**
