### PR TITLE
Make small fixes to allow for building

### PR DESCRIPTION
**Pull request by audrow**
This fixes a few things that were stopping me from building this with plot juggler from source.

### CODE REVIEW

**Comment by facontidavide** [comment]
On which version of ROS?

**Comment by audrow** [comment]
On ROS2 Rolling, from debian packages.

**Comment by facontidavide** [comment]
Then you should check the branch "rolling" and, if any chenage is needed, apply your PR to that, not "development"

**Comment by audrow** [comment]
Ah, I see these changes have recently been applied in other commits. Thank you.

**Comment by facontidavide** [comment]
but you helped me find another problem in development, so thanks YOU

**Comment by audrow** [comment]
No problem!

**Pull request closed without merging**
